<a href="https://colab.research.google.com/github/Udhay707/Pytorch-GAN/blob/main/Linear_Regression_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Crop Yield Prediction

With features like temp, rainfall, humidity, the problem is to predict the yield of apples and oranges in various regions

In [206]:
import numpy as np
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [207]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [209]:
import torch
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

Create random weight and biases to start with

In [208]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad = True)
w,b

(tensor([[ 0.2602, -1.2467, -0.8085],
         [ 3.0232,  2.1454, -1.1336]], requires_grad=True),
 tensor([-0.6930, -0.7585], requires_grad=True))

Model can be represented as X.W(Transpose) + b

In [ ]:
class Model:
    def __init__(self, w, b, learning_rate=1e-5):
        self.w = w
        self.b = b
        self.learning_rate = learning_rate
        self.__mse = 1e99
        self.__prev_mse = 1e100

    def predict(self, X):
        return X @ self.w + self.b  # Correct prediction formula

    def mse(self, prediction, target):
        return torch.mean((prediction - target) ** 2)  # MSE loss function

    def gradient_descent(self, pred, target):
        self.__prev_mse = self.__mse
        self.__mse = self.mse(pred, target)
        self.w.grad = None
        self.b.grad = None
        self.__mse.backward()  # Perform backpropagation
        with torch.no_grad():
            self.w -= self.w.grad * self.learning_rate  # Update weights
            self.b -= self.b.grad * self.learning_rate  # Update biases

    def linear_regression(self, input, target, max_iters=1000, tol=1e-6):
        for _ in range(max_iters):
            pred = self.predict(input)
            self.gradient_descent(pred, target)
            print(f'MSE: {self.__mse}')
            if abs(self.__mse - self.__prev_mse) < tol:
                break
        return self.predict(input)

The above class is created using iterations and implementation of gradiant descent and linear regression

In [212]:
model = Model(w, b)
model.linear_regression(inputs, targets)

MSE: 3.1405422687530518
MSE: 3.1356139183044434
MSE: 3.1307120323181152
MSE: 3.1258158683776855
MSE: 3.120922803878784
MSE: 3.11604642868042
MSE: 3.1111791133880615
MSE: 3.106316328048706
MSE: 3.1014742851257324
MSE: 3.096642255783081
MSE: 3.091804027557373
MSE: 3.0869734287261963
MSE: 3.082170009613037
MSE: 3.077355146408081
MSE: 3.0725719928741455
MSE: 3.0677754878997803
MSE: 3.0630135536193848
MSE: 3.0582292079925537
MSE: 3.053467273712158
MSE: 3.048729419708252
MSE: 3.04398250579834
MSE: 3.0392496585845947
MSE: 3.0345280170440674
MSE: 3.029818058013916
MSE: 3.0251169204711914
MSE: 3.0204148292541504
MSE: 3.0157313346862793
MSE: 3.011059284210205
MSE: 3.0063886642456055
MSE: 3.0017268657684326
MSE: 2.9970760345458984
MSE: 2.9924306869506836
MSE: 2.987788677215576
MSE: 2.9831693172454834
MSE: 2.978550672531128
MSE: 2.9739468097686768
MSE: 2.969339370727539
MSE: 2.964754819869995
MSE: 2.9601681232452393
MSE: 2.9556071758270264
MSE: 2.9510390758514404
MSE: 2.9464964866638184
MSE: 2.941

tensor([[ 57.1784,  70.4107],
        [ 81.8359, 100.1437],
        [119.5149, 133.9933],
        [ 21.3146,  37.3019],
        [101.0996, 118.1042]], grad_fn=<AddBackward0>)

In [213]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# Linear regression using PyTorch built-ins

In [214]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [215]:
from torch.utils.data import TensorDataset

train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [216]:
train_ds[[1,3,7,5]]

(tensor([[ 91.,  88.,  64.],
         [102.,  43.,  37.],
         [ 88., 134.,  59.],
         [ 74.,  66.,  43.]]),
 tensor([[ 81., 101.],
         [ 22.,  37.],
         [118., 132.],
         [ 57.,  69.]]))

In [217]:
from torch.utils.data import DataLoader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)


We can see train dl is shuffled wach time

In [222]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 87., 135.,  57.],
        [ 91.,  87.,  65.],
        [ 87., 134.,  58.]])
tensor([[103., 119.],
        [ 56.,  70.],
        [118., 134.],
        [ 80., 102.],
        [119., 133.]])


In [223]:
from torch import nn
model = nn.Linear(3, 2)# 3 inputs and 2 outputs
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4779,  0.1608, -0.2714],
        [ 0.4306,  0.4378,  0.3690]], requires_grad=True)
Parameter containing:
tensor([-0.4784, -0.3005], requires_grad=True)


In [224]:
preds = model(inputs)
preds

tensor([[-36.2635,  76.3363],
        [-47.1886, 101.0311],
        [-36.2526, 117.2340],
        [-52.3538,  76.1023],
        [-37.0163,  97.2743],
        [-36.9022,  76.3291],
        [-47.6207, 100.9623],
        [-37.0019, 118.0336],
        [-51.7151,  76.1095],
        [-36.8097,  97.2128],
        [-36.6957,  76.2675],
        [-47.8273, 101.0239],
        [-35.8205, 117.3028],
        [-52.5603,  76.1639],
        [-36.3775,  97.2815]], grad_fn=<AddmmBackward0>)

In [225]:
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [231]:
fit(100, nn.Linear(3,2), nn.functional.mse_loss, torch.optim.SGD(model.parameters(), lr=1e-5),  train_dl)

Epoch [10/100], Loss: 26311.5312
Epoch [20/100], Loss: 19976.9883
Epoch [30/100], Loss: 29913.3125
Epoch [40/100], Loss: 26470.3789
Epoch [50/100], Loss: 15027.8105
Epoch [60/100], Loss: 23450.3770
Epoch [70/100], Loss: 25026.0977
Epoch [80/100], Loss: 21497.8672
Epoch [90/100], Loss: 15152.6299
Epoch [100/100], Loss: 19996.6328
